version: 2

workflows:
  version: 2
  test:
    jobs:
      - build-python-3.6
      - build-python-3.7
      - build-python-3.8
      - build-python-3.9

jobs:
  build-python-3.9: &template
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Build source distribution and install package from it
          working_directory: ~/project/
          # Test that we can build a source distribution that can correctly
          # install from clean slate.
          # "python setup.py sdist" creates dist/pylangacq-x.y.z.tar.gz
          command: |
              pip install --progress-bar off --upgrade pip setuptools
              python setup.py sdist
              pip install dist/`ls dist/ | grep .tar.gz`
      - run:
          name: Check for PyPI compliance via twine
          working_directory: ~/project/
          command: |
            pip install twine
            twine check dist/`ls dist/ | grep .tar.gz`
      - run:
          name: Install the full development requirements
          working_directory: ~/project/
          command: pip install --progress-bar off -r dev-requirements.txt
      - run:
          name: Show installed Python packages
          command: pip list
      - run:
          name: Run linter
          working_directory: ~/
          # Avoid being able to do relative imports.
          # Test code by importing the *installed* library in site-packages.
          command: flake8 --ignore=E501,W503,E731 project/setup.py project/pylangacq
      - run:
          name: Run autoformat check
          working_directory: ~/
          # Avoid being able to do relative imports.
          # Test code by importing the *installed* library in site-packages.
          command: black --check project/setup.py project/pylangacq
      - run:
          name: Run python tests
          working_directory: ~/
          # Avoid being able to do relative imports.
          # Test code by importing the *installed* library in site-packages.
          command: pytest -vv --cov=project/pylangacq project/pylangacq
  build-python-3.6:
    <<: *template
    docker:
      - image: circleci/python:3.6
  build-python-3.7:
    <<: *template
    docker:
      - image: circleci/python:3.7
  build-python-3.8:
    <<: *template
    docker:
      - image: circleci/python:3.8
