version: 2

workflows:
  version: 2
  test:
    jobs:
      - build-python-3.6
      - build-python-3.7
      - build-python-3.8

jobs:
  build-python-3.6: &template
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Build source distribution and install package from it
          working_directory: ~/project/
          # Test that we can build a source distribution that can correctly
          # install from clean slate.
          # "python setup.py sdist" creates dist/pylangacq-x.y.z.tar.gz
          command: |
              pip install --progress-bar off --upgrade pip setuptools
              python setup.py sdist
              pip install dist/`ls dist/ | grep .tar.gz`
      - run:
          name: Install the full development requirements
          working_directory: ~/project/
          command: pip install --progress-bar off -r requirements.txt
      - run:
          name: Show installed Python packages
          command: pip list
      - run:
          name: Run linter
          working_directory: ~/
          # Avoid being able to do relative imports.
          # Test code by importing the *installed* library in site-packages.
          command: flake8 project/setup.py project/pylangacq
      - run:
          name: Run python tests
          working_directory: ~/
          # Avoid being able to do relative imports.
          # Test code by importing the *installed* library in site-packages.
          command: pytest -vv --cov=project/pylangacq project/pylangacq
  build-python-3.7:
    <<: *template
    docker:
      - image: python:3.7
  build-python-3.8:
    <<: *template
    docker:
      # TODO: Switch to python:3.8 after Python 3.8 is out in Oct/Nov 2019.
      - image: python:3.8-rc
