version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  pre-build:
    description: A check that needs to be done on only one supported Python version
    parameters:
      command-run:
        type: string
    docker:
      # Pick the highest Python 3.x version that civis-python is known to support
      - image: cimg/python:3.10
        #auth:
        #  username: $DOCKERHUB_USERNAME
        #  password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          working_directory: ~/project/
          command: << parameters.command-run >>

  build-python:
    parameters:
      python-version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python-version >>
        #auth:
        #  username: $DOCKERHUB_USERNAME
        #  password: $DOCKERHUB_PASSWORD
    resource_class: medium+
    steps:
      - checkout
      - run:
          # Test that we can build a source distribution that can correctly
          # install from clean slate.
          # "python -m build" creates dist/pylangacq-x.y.z.tar.gz and dist/pylangacq-x.y.z-py3-none-any.whl
          name: Build source distribution and install package from it
          working_directory: ~/project/
          command: |
              pip install -r dev-requirements.txt && \
              python -m build && \
              pip install dist/`ls dist/ | grep .whl`
      - run:
          name: Show installed Python packages
          command: pip list -v
      - run:
          name: Run python tests
          working_directory: ~/
          # Avoid being able to import pylangacq by relative import.
          # Test code by importing the *installed* pylangacq in site-packages.
          command: |
              pytest -vv --durations=0 --doctest-modules --cov=project/pylangacq --noconftest --junitxml=/tmp/testxml/report1.xml project/pylangacq && \
              pytest -vv --durations=0 --junitxml=/tmp/testxml/report2.xml project/docs/source
      - store_test_results:
          path: /tmp/testxml/

  build-python-win:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: Run tests on Windows
          shell: bash.exe
          # The codebase is available at c:\users\circleci\project,
          # We run commands at one directory above, so that we avoid being able to
          # import pylangacq by relative import when running the test suite.
          working_directory: c:\users\circleci
          command: |
            python --version && \
            pip install -r project/dev-requirements.txt && \
            pip install project/. && \
            pip list && \
            pytest -vv project/pylangacq && \
            pytest -vv project/docs/source

workflows:
  version: 2
  build-and-test:
    jobs:
      - pre-build:
          name: flake8
          command-run: |
            pip install -r dev-requirements.txt && \
            flake8 --config=setup.cfg pylangacq
      - pre-build:
          name: black
          command-run:  |
            pip install -r dev-requirements.txt && \
            black --check pylangacq
      - pre-build:
          name: twine
          command-run: |
            pip install -r dev-requirements.txt && \
            python -m build && \
            twine check dist/`ls dist/ | grep .tar.gz` && \
            twine check dist/`ls dist/ | grep .whl`
      - pre-build:
          name: safety
          command-run: |
            pip install -e . && \
            pip install --upgrade safety && \
            safety --version && \
            pip freeze | safety check --stdin
      - pre-build:
          name: bandit
          command-run: |
            pip install --upgrade bandit && \
            bandit --version && \
            bandit -r pylangacq -x pylangacq/tests
      - build-python:
          requires:
            - flake8
            - black
            - twine
            - safety
            - bandit
          matrix:
            parameters:
              python-version: ["3.7", "3.8", "3.9", "3.10"]
      - build-python-win:
          requires:
            - flake8
            - black
            - twine
            - safety
            - bandit
