version: 2.1

orbs:
  python: circleci/python@1.2.0

jobs:
  pre-build:
    description: Install and run a Python standalone package
    parameters:
      command-name:
        type: string
      command-run:
        type: string
    docker:
      - image: cimg/python:3.9
        #auth:
        #  username: $DOCKERHUB_USERNAME
        #  password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Create custom requirements
          command: grep << parameters.command-name >> dev-requirements.txt > << parameters.command-name >>-dev-requirements.txt
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: << parameters.command-name >>-dev-requirements.txt
          cache-version: << parameters.command-name >>-v1
      - run:
          working_directory: ~/
          command: << parameters.command-run >>

  build-python:
    parameters:
      python-version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python-version >>
        #auth:
        #  username: $DOCKERHUB_USERNAME
        #  password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          # Intentionally not using CircleCI's "python/install-packages" step,
          # because we don't want to install packages from any requirements.txt
          # just yet.
          # Test that we can build a source distribution that can correctly
          # install from clean slate.
          # "python setup.py sdist" creates dist/pylangacq-x.y.z.tar.gz
          name: Build source distribution and install package from it
          working_directory: ~/project/
          command: |
              pip install --progress-bar off --upgrade pip setuptools
              python setup.py sdist
              pip install dist/`ls dist/ | grep .tar.gz`
      - run:
          name: Install the full development requirements
          working_directory: ~/project/
          command: pip install --progress-bar off -r dev-requirements.txt
      - run:
          name: Check for PyPI compliance via twine
          working_directory: ~/project/
          command: twine check dist/`ls dist/ | grep .tar.gz`
      - run:
          name: Show installed Python packages
          command: pip list -v
      - run:
          name: Run python tests
          working_directory: ~/
          # Avoid being able to import pylangacq by relative import.
          # Test code by importing the *installed* pylangacq in site-packages.
          command: |
              pytest -vv --doctest-modules --cov=project/pylangacq --noconftest --junitxml=/tmp/testxml/report1.xml project/pylangacq
              pytest -vv --junitxml=/tmp/testxml/report2.xml project/docs/source
      - store_test_results:
          path: /tmp/testxml/

workflows:
  version: 2
  build-and-test:
    jobs:
      - pre-build:
          name: flake8
          command-name: flake8
          command-run: flake8 --config=project/setup.cfg project/setup.py project/pylangacq
      - pre-build:
          name: black
          command-name: black
          command-run: black --check project/setup.py project/pylangacq
      - build-python:
          requires:
            - flake8
            - black
          matrix:
            parameters:
              python-version: ["3.6", "3.7", "3.8", "3.9"]
